[default]
extend-ignore-identifiers-re = [
    "mmaped",
    "arange",
    "cudaDevAttrMaxSharedMemoryPerBlockOptin",
    "setp",
]

extend-ignore-words-re = [
    # load-test tool name
    "\\bwrk\\b",
    # GitHub markdown anchor slug for "You're"
    "\\byoure\\b",
]
